config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'home#index'
  
  resources :articles, only: [:show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]
  resources :pages, only: [:show]

  namespace :admin do
    root 'home#index'
    resources :articles, except: [:show]
    post "articles/:id/hide" => "articles#hide", as: :hide_article
    post "articles/:id/publish" => "articles#publish", as: :publish_article
    resources :categories, except: [:show]
    resources :tags, except: [:show]
    resources :pages, except: [:show]
    resources :courses, except: [:show]
    resources :videos, except: [:show]
  end
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  has_rich_text :content
  friendly_id :title, use: :slugged, slug_column: :permalink
  
  has_many :article_categories, dependent: :destroy
  has_many :article_tags, dependent: :destroy

  has_many :categories, through: :article_categories
  has_many :tags, through: :article_tags
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  before_action :set_article, only: [:edit, :hide, :publish, :update, :destroy]

  def index
    @articles = Article.all.paginate(page: params[:page] || 1, per_page: 50).order(:created_at => :desc)
  end
  
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_articles_path, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def publish
    respond_to do |format|
      if @article.update(published: true)
        format.html { redirect_to admin_articles_path, notice: 'Article was successfully published.' }
      else
        format.html { render :edit }
      end
    end
  end

  def hide
    respond_to do |format|
      if @article.update(published: false)
        format.html { redirect_to admin_articles_path, notice: 'Article was successfully unpublished.' }
      else
        format.html { render :edit }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to admin_articles_path, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private

  def set_article
    @article = Article.friendly.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :permalink, :reading_time, :thumbnail_url, :published, :content)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  
  def show
  end

  private

  def set_article
    @article = Article.friendly.find(params[:id])
  end
end

app/views/admin/articles/_form.html.erb
<%= form_with(model: article, url: admin_article_path) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :permalink %><br />
    <%= form.text_field :permalink %>
  </div>

  <div class="field">
    <%= form.label :reading_time %><br />
    <%= form.number_field :reading_time %>
  </div>

  <div class="field">
    <%= form.label :thumbnail_url %><br />
    <%= form.file_field :thumbnail_url %>
  </div>

  <div class="field">
    <%= form.label :content %><br />
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<%= render 'form', article: @article, admin_article_path: admin_article_path(@article) %>

app/views/admin/articles/index.html.erb
<h1>Listagem artigos</h1>
<%= notice %>
<table>
  <thead>
    <tr>
      <th>Título</th>
      <th>Data de criação</th>
      <th>Data de atualização</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.created_at %></td>
        <td><%= article.updated_at %></td>
        <% if article.published? %>
          <td><%= link_to "Esconder", admin_hide_article_path(article), method: :post %></td>
        <% else %>
          <td><%= link_to "Publicar", admin_publish_article_path(article), method: :post %></td>
        <% end %>
        <td><%= link_to "Editar", edit_admin_article_path(article) %></td>
        <td><%= link_to "Deletar", admin_article_path(article), method: :delete, data: { confirm: "Você tem certeza?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>