config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'home#index'
  
  resources :articles, only: [:show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]
  resources :pages, only: [:show]

  namespace :admin do
    root 'home#index'
    resources :articles, except: [:show]
    post "articles/:id/hide" => "articles#hide", as: :hide_article
    post "articles/:id/publish" => "articles#publish", as: :publish_article
    resources :categories, except: [:show]
    resources :tags, except: [:show]
    resources :pages, except: [:show]
    resources :courses, except: [:show]
    resources :videos, except: [:show]
  end
end

app/views/shared/_about.html.erb
<div class="about">
  <div class="profile-picture">
    <%= image_tag "/images/profile.jpeg" %>
  </div>
  <div class="social-links">
    <ul>
      <li><%= link_to "Linkedin", "https://www.linkedin.com/in/lucasayb/", class: "social-linkedin", rel: "nofollow", target: "_blank" %></li>
      <li><%= link_to "Instagram", "https://www.instagram.com/lucasyamamoto1997", class: "social-instagram", rel: "nofollow", target: "_blank" %></li>
      <li><%= link_to "Twitter", "https://twitter.com/lucasayb", class: "social-twitter", rel: "nofollow", target: "_blank" %></li>
      <li><%= link_to "Email", "mailto:lucasayb97@gmail.com", class: "social-email", rel: "nofollow", target: "_blank" %></li>
    </ul>
  </div>
</div>

app/views/shared/_article.html.erb
<%= link_to article_path(article), class: "article-summary" do %>
  <div class="article-summary-thumb"><%= image_tag article.thumbnail_url, alt: article.title %></div>
  <span class="article-summary-date">
    <%= time_tag article.created_at do %>
      <%= article.created_at.strftime('%d/%m/%Y') %>
    <% end %>
  </span>
  <h3 class="article-summary-title"><%= article.title %></h3>
  <div class="article-summary-reading-time">
    <span class="article-summary-reading-time-label">Tempo médio de leitura: </span>
    <span class="article-summary-reading-time-text"><%= article.reading_time %> minutos</span>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="container">
  <header class="header-main">
    <div class="hamburguer-icon">
      <span class="hamburguer-icon-line-1"></span>
      <span class="hamburguer-icon-line-2"></span>
      <span class="hamburguer-icon-line-3"></span>
    </div>
    <div class="site-title">Lucas Yamamoto</div>
  </header>
</div>

<%#= render :partial => "shared/navbar" %>

app/views/shared/_navbar.html.erb
<nav class="navbar-main">
  <ul>
    <% @pages.each do |page| %>
      <li><%= link_to page.title, page.permalink %></li>
    <% end %>
  </ul>
</nav>
<div class="navbar-background"></div>

app/views/shared/_welcome.html.erb
<div class="container">
  <div class="welcome">
    <h2>CTO na Codeby</h2>
    <p>Sou um desenvolvedor Web e CTO da CodeBy. Busco estar por dentro das tecnologias no mercado de e-commerce e programação no geral, sempre focando em me renovar e buscar por soluções úteis e práticas para mim e para as empresas para as quais prestamos serviços.</p>
  </div>
</div>